version: '3'
services:
  php:
    build:
        context: ./docker/php
    volumes:
        - './app:/var/www/html'
    container_name: php
    depends_on:
      - mysql

  mysql:
      image: mysql:8
      environment:
         MYSQL_ROOT_PASSWORD: root
      container_name: db
      volumes:
        - './docker/mysql:/var/lib/mysql'
      ports:
        - 3306:3306
      restart: always

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    container_name: nginx
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d/'
      - './app:/var/www/html'
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
      - php